---
- include: clean.yml
  when: dcm4chee_upgrade
- include: install.yml
  tags: install
- include: postgresql.yml
  tags: postgresql
- include: openldap.yml
  tags: openldap
- include: wildfly.yml
  tags: wildfly
- include: jlsl.yml
  tags: jlsl
